file(MAKE_DIRECTORY "${WORK}")
file(WRITE "${WORK}/config.json" "{}")
file(WRITE "${WORK}/input.cfg"
"Station,Device,1999\n1,1A,0D\n1,IA,A,,A,2,1,0,-32768,32767,1,1,P\n50\n1\n1000,2\n01/01/2020,00:00:00.000000\n01/01/2020,00:00:00.001000\nASCII\n1\n")
file(WRITE "${WORK}/input.dat" "1,0,1\n2,1000,2\n")
file(REMOVE "${WORK}/evidence.json")
execute_process(COMMAND "${CLI}" summarize "${WORK}/config.json" "${WORK}/input.cfg"
    "${WORK}/input.dat" "${WORK}/evidence.json" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Installed CLI failed: ${result}: ${error}")
endif()
file(READ "${WORK}/evidence.json" evidence)
if(NOT evidence MATCHES "\"samples\": 2" OR NOT evidence MATCHES "\"mean\": 4")
    message(FATAL_ERROR "Installed CLI produced incorrect evidence")
endif()
execute_process(COMMAND "${CLI}" summarize "${WORK}/config.json" "${WORK}/input.cfg"
    "${WORK}/input.dat" "${WORK}/evidence.json" RESULT_VARIABLE result)
if(NOT result EQUAL 1)
    message(FATAL_ERROR "CLI must reject an existing output")
endif()
file(READ "${WORK}/evidence.json" after)
if(NOT after STREQUAL evidence)
    message(FATAL_ERROR "CLI changed the existing output")
endif()
